<a href="https://colab.research.google.com/github/surekavin/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆) 
import numpy as np

In [ ]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#### 4.  How to find the memory size of any array (★☆☆)
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [ ]:
#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#### 8.  Reverse a vector (first element becomes last) (★☆☆)
x=np.arange(10,50)
x=x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
#### 11. Create a 3x3 identity matrix (★☆☆)
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
z=np.random.uniform((3,3,3))
print(z)

[1.58167872 2.28384895 2.94761681]


In [ ]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
z=np.random.random((10,10))
zmin,zmax=z.min(),z.max()
print(zmin,zmax)

0.01117543525952125 0.9956777434560328


In [ ]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
z=np.random.random(30)
m=z.mean()
print(m)

0.4285606932447965


In [ ]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
x=np.ones((3,3))
x=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#### 17. What is the result of the following expression? (★☆☆)
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


In [ ]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
array=np.array([[0,1],[1,0]])
z=np.tile(array,(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#### 22. Normalize a 5x5 random matrix (★☆☆) 
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.72155246 0.38951315 0.31060446 0.21416394 0.55678966]
 [0.88487791 0.48111922 0.35432393 0.25534835 0.        ]
 [0.35479956 0.71856258 0.82638562 0.66575262 0.96407979]
 [0.07990975 0.18989922 0.9650577  0.87401809 1.        ]
 [0.3509261  0.01448253 0.4408151  0.36967051 0.54891135]]


In [ ]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
color=np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
z=np.arange(11)
z[(3<z)&(z<8)]*=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
#### 26. What is the output of the following script? (★☆☆) 
print(sum(range(5),-1))

9


In [ ]:
#### 27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

In [ ]:
#### 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#### 29. How to round away from zero a float array ? (★☆☆)
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))
print(np.where(z<0,np.ceil(z),np.floor(z)))

[ -8.  -8.  -7.  10.  -2. -10.  -4.   5.  -1.  10.]
[-7. -7. -6.  9. -1. -9. -3.  4. -0.  9.]


In [ ]:
#### 30. How to find common values between two arrays? (★☆☆)
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[2 3 4 6 8]


In [ ]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
defaults=np.seterr(all="ignore")
z=np.ones(1)/0
_=np.seterr(**defaults)
with np.errstate(all="ignore"):
  np.arange(3)/0

In [ ]:
#### 32. Is the following expressions true? (★☆☆)
import math
np.sqrt(-1)==np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [ ]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)


In [ ]:
#### 34. How to get all the dates corresponding to the month of July 2016?
z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
#### 36. Extract the integer part of a random array using 5 different methods
z=np.random.uniform(0,10,10)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[3. 7. 7. 0. 5. 8. 1. 1. 4. 8.]
[3. 7. 7. 0. 5. 8. 1. 1. 4. 8.]
[3. 7. 7. 0. 5. 8. 1. 1. 4. 8.]
[3 7 7 0 5 8 1 1 4 8]
[3. 7. 7. 0. 5. 8. 1. 1. 4. 8.]


In [ ]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
z=np.zeros((5,5))
z+=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
  for x in range(10):
    yield x
z=np.fromiter(generate(),dtype=float,count=-1)
print(z)    

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
z=np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
z=np.random.random(10)
z.sort()
print(z)

[0.11578112 0.21306719 0.22340127 0.45689565 0.52545507 0.5500071
 0.59396277 0.72154725 0.74391663 0.8715717 ]


In [ ]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
z=np.arange(10)
np.add.reduce(z)

45

In [ ]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


In [ ]:
#### 43. Make an array immutable (read-only) (★★☆)
z=np.zeros(0)
z.flags.writeable=False
z[0]=1

ValueError: ignored

In [ ]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
z=np.random.random((10,2))
X,Y=z[:,0],z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[1.12305971 0.81690563 0.91124426 0.63127728 0.88211502 1.21379593
 0.55141847 1.00616058 0.5710693  0.42700259]
[0.78355665 0.14180087 0.71756386 1.48657882 0.57731422 0.63123136
 0.27498967 1.16646008 1.08213685 1.51507545]


In [ ]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.93088573 0.38868698 0.         0.64966686 0.32462279 0.73002557
 0.57702989 0.47829732 0.05583646 0.83682321]


In [ ]:
#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))


3638.163637117973


In [ ]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#### 49. How to print all the values of an array? (★★☆)
np.set_printoptions()
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(z-v)).argmin()
print(z[index])

16


In [ ]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [ ]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy

import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.42508691 0.59300326 0.53865952 0.58975355 0.55060669
  0.25640184 0.3634339  0.23590587 0.31237251]
 [0.42508691 0.         0.9708367  0.26638556 0.49823573 0.83705361
  0.22032996 0.75333854 0.4258123  0.18933793]
 [0.59300326 0.9708367  0.         0.95636851 0.82482252 0.86330567
  0.75356137 0.58005574 0.79133006 0.79776078]
 [0.53865952 0.26638556 0.95636851 0.         0.26664752 1.04375024
  0.28367904 0.90116414 0.635618   0.22917567]
 [0.58975355 0.49823573 0.82482252 0.26664752 0.         1.13858607
  0.39360745 0.93734306 0.76331269 0.36420265]
 [0.55060669 0.83705361 0.86330567 1.04375024 1.13858607 0.
  0.76977743 0.28581874 0.41282755 0.81893088]
 [0.25640184 0.22032996 0.75356137 0.28367904 0.39360745 0.76977743
  0.         0.61769308 0.37421629 0.05607567]
 [0.3634339  0.75333854 0.58005574 0.90116414 0.93734306 0.28581874
  0.61769308 0.         0.36497513 0.67305638]
 [0.23590587 0.4258123  0.79133006 0.635618   0.76331269 0.41282755
  0.37421629 0.36497

In [ ]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#### 54. How to read the following file? (★★☆)
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [ ]:
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
  print(index,value)
for index in np.ndindex(z.shape):
  print(index,z[index])  

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#### 58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.21923278 -0.342218   -0.24974546  0.38996335  0.24622824  0.45959691
   0.07628391 -0.37750391 -0.11280446 -0.30903335]
 [ 0.0678576  -0.09298089  0.29174659 -0.46172771  0.30619268  0.31754871
  -0.27228032 -0.37026607 -0.0558014   0.2697108 ]
 [ 0.08029004  0.33164432 -0.16733933 -0.21225864  0.49918316 -0.15553116
  -0.28108081 -0.10421076  0.17970131 -0.17039812]
 [ 0.47235158  0.1428788  -0.19838384 -0.20500682 -0.0827169   0.08097532
   0.33381938  0.36500489 -0.43365197 -0.47527043]
 [-0.2288351   0.29115968 -0.09234577 -0.32944929  0.24301616  0.35093269
   0.07229193 -0.29546828  0.35030418 -0.36160619]]


In [ ]:
#### 59. How to sort an array by the nth column? (★★☆) 
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[7 9 8]
 [6 5 1]
 [2 0 8]]
[[2 0 8]
 [6 5 1]
 [7 9 8]]


In [ ]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [3]:
#### 61. Find the nearest value from a given value in an array (★★☆) 
Z=np.random.uniform(0,1,10)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

0.5996229668370092


In [4]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it: z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [5]:
#### 63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [6]:
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
z=np.ones(10)
i=np.random.randint(0,len(z),20)
z+=np.bincount(i,minlength=len(z))
print(z)

[2. 2. 6. 1. 4. 3. 4. 3. 2. 3.]


In [7]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
x=[1,2,3,4,5,6,7]
y=[1,3,2,5,7,8,9]
z=np.bincount(x,y)
print(z)

[0. 1. 3. 2. 5. 7. 8. 9.]


In [8]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
w,h=16,16
i=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f=i[...,0]*(256*256)+i[...,1]*256+i[...,2]
n=len(np.unique(f))
print(n)

8


In [9]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[40 71 72 43]
 [69 68 51 53]
 [58 69 64 64]]


In [10]:
#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
d=np.random.uniform(0,1,100)
s=np.random.randint(0,10,100)
d_sums=np.bincount(s,weights=d)
d_counts=np.bincount(s)
d_means=d_sums/d_counts
print(d_means)


[0.62143286 0.52398802 0.53895281 0.43346273 0.42487028 0.37362054
 0.42142708 0.529042   0.67684984 0.38351458]


In [11]:
#### 69. How to get the diagonal of a dot product? (★★★)
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.61921617, 0.91229491, 0.42124504, 1.27974561, 1.38826809])

In [12]:
#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
z=np.array([1,2,3,4,5])
nz=3
z0=np.zeros(len(z)+(len(z)-1)*(nz))
z0[::nz+1]=z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [13]:
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [14]:
#### 72. How to swap two rows of an array? (★★★)
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  9) ( 0, 54) ( 3, 80) ( 3, 82) ( 8, 21) ( 8, 90) ( 9, 54) (21, 90)
 (31, 53) (31, 66) (33, 46) (33, 72) (33, 96) (33, 99) (39, 48) (39, 83)
 (41, 68) (41, 73) (42, 56) (42, 78) (46, 99) (48, 83) (49, 67) (49, 90)
 (53, 66) (56, 78) (67, 90) (68, 73) (72, 96) (80, 82)]


In [20]:
#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


In [21]:
#### 75. How to compute averages using a sliding window over an array? (★★★) 

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [22]:
#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [23]:
#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([-1.68748164e-01, -4.17087339e-01,  4.41246077e-01, -2.19928191e-01,
        5.34287729e-01,  5.56440657e-01,  2.08477705e-01,  2.98280175e-01,
       -6.33642535e-01, -4.76159598e-01,  2.16406299e-01, -3.54061694e-01,
       -8.29699015e-01, -2.19469715e-02,  6.22740530e-01,  3.36374803e-01,
        6.14907342e-01,  9.80887030e-01,  2.08212610e-01,  5.04402919e-02,
        7.20839828e-01,  2.81016397e-01,  6.52584629e-01,  4.02496957e-01,
       -4.16514435e-01,  3.24494891e-01,  8.95777431e-01,  8.85364349e-01,
        3.15869708e-01,  4.96111723e-01,  2.20380349e-01, -4.64968642e-01,
       -1.70890208e-01, -5.10798796e-02,  1.31618530e-04,  9.89607746e-01,
        5.35178187e-01,  6.72167149e-01, -7.59693374e-01, -1.01568242e-01,
        8.53316803e-01,  9.45528855e-02,  5.25672119e-01, -4.63103144e-01,
       -2.18120770e-01, -7.50386859e-02, -5.81366461e-02, -1.75132842e-02,
        3.92142089e-01,  2.91785715e-01, -1.75481862e-01,  8.99077113e-02,
        9.23621927e-01, -

In [24]:
#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.43721084 15.78386629  8.4821823   6.3419179  11.86530079  0.41339867
 10.20365883 12.78885923 10.25063046  6.68177413]


In [25]:
#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.0754762   5.20159529  2.83236493  5.70848105  3.89267961  7.38606683
   6.10857401  9.14312764 11.08009482  4.45079885]
 [ 8.16525708  4.50570806 18.03506452 13.45347994 15.38198015  4.47521543
   0.42448407  2.52769238  8.28486197  5.92758535]
 [ 0.2598121   6.60777789  0.65349076  7.19511208  5.74408618  7.36979445
   7.95282507 11.24912301 12.71996056  4.23134391]
 [ 3.21667367  4.33782918  4.24124142  4.70335978  2.66382857  7.33683977
   4.94767546  7.79646043  9.98021263  4.53327663]
 [ 2.63846179  7.48204229  8.84207669  4.33042381  5.50883507  0.65991204
   5.30200426  5.37719421  1.20377634  2.9906953 ]
 [ 8.76698911  0.85095001 12.49570657  2.70305739  5.63342213  4.9809068
   0.76016289  0.42847603  2.16814993  2.96025107]
 [ 2.43305853 13.95987609  7.76342423  9.16924779  8.62423827  8.2632581
  10.23303038  8.33741324  3.00980046 10.65325432]
 [ 1.9575614  10.12373792 12.17676198 11.22789682 11.68536372  6.93252028
   5.810931    3.74403182  5.47270024  8.91803679]
 [

In [26]:
#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[3 7 4 7 8 2 5 9 3 8]
 [4 0 2 8 7 2 9 8 6 2]
 [5 1 7 1 5 7 3 4 7 5]
 [1 3 0 3 0 0 3 4 4 5]
 [4 9 8 6 3 7 0 8 0 5]
 [6 7 8 2 4 0 5 7 8 3]
 [9 3 9 2 0 9 3 6 5 4]
 [4 5 0 5 6 4 3 5 5 8]
 [2 7 1 4 6 6 5 6 5 4]
 [8 8 4 8 9 7 6 7 1 0]]
[[0 0 0 0 0]
 [0 3 7 4 7]
 [0 4 0 2 8]
 [0 5 1 7 1]
 [0 1 3 0 3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [27]:
#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [28]:
#### 82. Compute a matrix rank (★★★)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


In [29]:
#### 83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


In [30]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 1]
   [1 1 4]
   [0 2 1]]

  [[0 1 3]
   [1 4 2]
   [2 1 3]]

  [[1 3 3]
   [4 2 2]
   [1 3 4]]

  [[3 3 3]
   [2 2 2]
   [3 4 1]]

  [[3 3 1]
   [2 2 0]
   [4 1 3]]

  [[3 1 3]
   [2 0 0]
   [1 3 0]]

  [[1 3 1]
   [0 0 4]
   [3 0 3]]

  [[3 1 1]
   [0 4 2]
   [0 3 0]]]


 [[[1 1 4]
   [0 2 1]
   [2 3 2]]

  [[1 4 2]
   [2 1 3]
   [3 2 4]]

  [[4 2 2]
   [1 3 4]
   [2 4 4]]

  [[2 2 2]
   [3 4 1]
   [4 4 1]]

  [[2 2 0]
   [4 1 3]
   [4 1 4]]

  [[2 0 0]
   [1 3 0]
   [1 4 1]]

  [[0 0 4]
   [3 0 3]
   [4 1 0]]

  [[0 4 2]
   [0 3 0]
   [1 0 3]]]


 [[[0 2 1]
   [2 3 2]
   [4 1 1]]

  [[2 1 3]
   [3 2 4]
   [1 1 1]]

  [[1 3 4]
   [2 4 4]
   [1 1 1]]

  [[3 4 1]
   [4 4 1]
   [1 1 4]]

  [[4 1 3]
   [4 1 4]
   [1 4 0]]

  [[1 3 0]
   [1 4 1]
   [4 0 1]]

  [[3 0 3]
   [4 1 0]
   [0 1 3]]

  [[0 3 0]
   [1 0 3]
   [1 3 4]]]


 [[[2 3 2]
   [4 1 1]
   [0 3 2]]

  [[3 2 4]
   [1 1 1]
   [3 2 3]]

  [[2 4 4]
   [1 1 1]
   [2 3 1]]

  [[4 4 1]
   [1 1 4]
   [3 1 3]]

  [[4 1 4]
   

In [31]:
#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  9 14 16  2]
 [ 9  0 12  1  8]
 [14 12  1 42 10]
 [16  1 42  9  9]
 [ 2  8 10  9  8]]


In [32]:
#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [33]:
#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [34]:
#### 88. How to implement the Game of Life using numpy arrays? (★★★)
def iterate(Z):
  
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [35]:
#### 89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [36]:
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [37]:
#### 91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [38]:
#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: ignored

In [39]:
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 4 5]


In [40]:
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 2 0]
 [1 3 2]
 [0 1 3]
 [4 1 3]
 [4 4 3]
 [0 1 2]
 [4 1 0]
 [2 3 1]
 [1 0 0]
 [3 3 4]]
[[2 2 0]
 [1 3 2]
 [0 1 3]
 [4 1 3]
 [4 4 3]
 [0 1 2]
 [4 1 0]
 [2 3 1]
 [1 0 0]
 [3 3 4]]
[[2 2 0]
 [1 3 2]
 [0 1 3]
 [4 1 3]
 [4 4 3]
 [0 1 2]
 [4 1 0]
 [2 3 1]
 [1 0 0]
 [3 3 4]]


In [41]:
#### 95. Convert a vector of ints into a matrix binary representation (★★★)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [42]:
#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]


In [43]:
#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.13204472, 0.08677738, 0.14662607, 0.0201398 , 0.12264153,
        0.10304362, 0.04625793, 0.00921164, 0.03796394, 0.04964087],
       [0.06432192, 0.04227119, 0.07142482, 0.00981055, 0.05974142,
        0.05019484, 0.02253326, 0.0044872 , 0.01849308, 0.02418117],
       [0.2668342 , 0.17535856, 0.2963    , 0.04069824, 0.24783237,
        0.20822916, 0.0934774 , 0.01861477, 0.07671701, 0.1003136 ],
       [0.46725113, 0.3070689 , 0.51884844, 0.07126635, 0.43397717,
        0.36462834, 0.16368749, 0.03259616, 0.13433852, 0.17565829],
       [0.48894835, 0.32132791, 0.54294163, 0.07457566, 0.45412928,
        0.38156017, 0.17128846, 0.03410979, 0.14057664, 0.18381514],
       [0.03953297, 0.02598034, 0.04389849, 0.00602967, 0.03671774,
        0.03085031, 0.0138492 , 0.00275788, 0.01136605, 0.01486202],
       [0.05461848, 0.03589427, 0.06064985, 0.00833055, 0.05072898,
        0.04262257, 0.01913395, 0.00381027, 0.01570326, 0.02053326],
       [0.2189697 , 0.14390289, 0.2431499

In [44]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)


In [45]:
#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [46]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17700018  0.2255351 ]
